import React, { useState } from 'react';

import { Content } from './styles';
import { Container, Title } from "../../styles/styles";

export default function Experiences() {
  const [work, setWork] = useState("kurier");
  
  function getWork(change) {
    setWork(change);
  }

  return (
    <Container id="experiences">
      <Title>Experiences</Title>
      <Content>
        <ul>
          <li className="disabled"><button></button></li>
          <li className={work === "kurier" ? "active" : ""}><button onClick={() => getWork("kurier")}></button></li>
          <li className={work === "mv" ? "active" : ""}><button onClick={() => getWork("mv")}></button></li>
        </ul>
        <div className="works">
          <div id="kurier" className={work === "kurier" ? "visible" : "not-visible"}>
            <span>Kurier (Mk Tecnologia em Informação Ltda)</span>
            <h3>Agosto 2019 - Fevereiro 2020</h3>

            <p>Analysis, development and maintenance of software systems for legal management.</p>
            <p>Developer of the desktop and web version of Kurier Meridio using Delphi 10, AngularJs, SQL Server and SOAP.</p>
            <p>Migration of the database of new customers to Kurier Meridio, creation of scripts to create reports exported in the system, analysis of scripts generated by the support.</p>
          </div>
          <div id="mv" className={work === "mv" ? "visible" : "not-visible"}>
            <span>MV Sistemas</span>
            <h3>Agosto 2018 - Agosto 2019</h3>

            <p>Analysis, development and maintenance of software systems for hospital management.</p>
            <p>Developer of the international version of SoulMV using proprietary framework based on Spring Boot, GitLab for versioning, Oracle for database and Java programming language.</p>
            <p>Systems tested manually to ensure compatibility and responsiveness to customers.</p>
          </div>
        </div>
      </Content>
    </Container>
  );
}
