import React, { useState } from 'react';

import { Content } from './styles';
import { Container, Title } from "../../styles/styles";

const experiences = [
  {
    "company": "Thoughtworks",
    "position": "Software Developer Consultant",
    "website": "https://www.thoughtworks.com",
    "startDate": "2021-04-05",
    "endDate": "",
    "summary": []
  },
  {
    "company": "Mesa Mobile Thinking",
    "position": "Full Stack Developer",
    "website": "https://www.mesainc.com.br",
    "startDate": "2020-03-02",
    "endDate": "2021-04-05",
    "summary": [
      'Developer for projects with technologies such as AdonisJs, PostgreSQL, SQL Server for backend development, Vue.Js for frontend development, Gitlab for versioning and Heroku for deploy.'
    ]
  },
  {
    "company": "Kurier (Mk Tecnologia em Informação Ltda)",
    "position": "Full Stack Developer",
    "website": "https://kuriertecnologia.com.br",
    "startDate": "2019-08-01",
    "endDate": "2020-02-29",
    "summary": [
      'Analysis, development and maintenance of software systems for legal management.',
      'Developer of the desktop and web version of Kurier Meridio using Delphi 10, AngularJs, SQL Server and SOAP.',
      'Migration of the database of new customers to Kurier Meridio, creation of scripts to create reports exported in the system, analysis of scripts generated by the support.'
    ]
  },
  {
    "company": "MV Sistemas",
    "position": "Full Stack Developer",
    "website": "https://www.mv.com.br",
    "startDate": "2018-08-01",
    "endDate": "2019-08-01",
    "summary": [
      'Analysis, development and maintenance of software systems for hospital management.',
      'Developer of the international version of SoulMV using proprietary framework based on Spring Boot, GitLab for versioning, Oracle for database and Java programming language.',
      'Systems tested manually to ensure compatibility and responsiveness to customers.'
    ]
  },
]

const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export default function Experiences() {
  const [currentExperience, setCurrentExperience] = useState(0);

  function formattedDate(date) {
    if(!date) return 'Present';
    const currentDate = new Date(date);

    return `${months[currentDate.getMonth()]} ${currentDate.getFullYear()}`;
  }

  return (
    <Container id="experiences">
      <Title>Experiences</Title>
      <Content>
        <ul>
          {experiences.map((experience, index) => 
            <li key={experience.company} className={currentExperience === index ? "active" : ""}>
              <button onClick={() => setCurrentExperience(index)}></button>
            </li>
          )}      
        </ul>

        <div className="works">
          <a href={experiences[currentExperience].website}>
            {experiences[currentExperience].company}
          </a>
          <span>{experiences[currentExperience].position}</span>
          <h3>
            {formattedDate(experiences[currentExperience].startDate)} - {formattedDate(experiences[currentExperience].endDate)}
          </h3>


          {experiences[currentExperience].summary.map(((paragraph, index) => 
            <p key={index}>{paragraph}</p>
          ))}
        </div>
      </Content>
    </Container>
  );
}
